# ID - Amount - Data Value
items:
  - 4 10

# Number of items for random item selection ; -1 to disable
# X number of items will be selected from the items listed above
# E.g. if 8 items listed, and numOfItems = 3, then 3 of those item/
# amount pairs will be chosen and used.
numOfItems: 1

# Mob - Quantity
mobs:
  - pig 1
  
# Number of mobs for random item selection ; -1 to disable
# X number of mobs will be selected from the mobs listed above
# E.g. if 8 mobs listed, and numOfMobs = 3, then 3 of those item/
# amount pairs will be chosen and used.
numOfMobs: 1

# global number of objectives ; -1 to disable
# this will select objectives without defining its type
# e.g. if globalNumOfObjectives = 3 will select 3 random objectives(mob or item)
# If this is set to 0 OR numOfItems and numOfMobs are 0, the plugin
# turns into a giveaway fest.
globalNumOfObjectives: -1

# To enable riddle mode. Riddle mode replace objectives with set messages.
# If you enable this, make sure the riddles match up with each individual
# objective. (Make sure that there's enough riddles of each type, and that they're
# at the SAME order.) 
riddleMode: false

# Put riddles for ITEMS here, if riddleMode enabled. Note that if quantity is important, 
# that you specify that in the riddle (see riddle 2 in default config).
itemRiddles:
  - "1. First riddle (e.g. I'm like stone, but cracked!)"
  - "2. For example, for 10 of an item, you might want to put (10) at the end"

#Put riddles for MOBS here, if riddleMode enabled. Note that if quantity is important, 
# that you specify that in the riddle.
mobRiddles:
  - "1. If you give me a carrot, we can ride together real fast!"

# Reward listing usage as follows
# ID Amount DataValue Enchant:Level;Enchant:Level=Probability(1-100)
# Example: - 276 1 16:5;21:3=50 will add 1 Diamond Sword with Sharpness V and Looting III,
# with probability weight of 50. The probability of the item depends on the sum of
# all the weights. Defaults to 100 if not set. 
rewards:
  - 357 1

#Use reward weighted probability?
useProbability: false

# Number of rewards for random item selection ; 0 to disable
# X number of items will be selected from the items listed above
# E.g. if 8 items listed, and numOfRewards = 3, then 3 of those item/
# amount pairs will be chosen and used.
numOfRewards: 1

# Money awarded to winner (Must have Vault to use!)
moneyReward: 0

#Experience awarded to winner
expReward: 0

# global number of rewards ; 0 to disable
# this will select rewards without defining its type
# e.g. if globalNumOfRewards = 5 will select 5 random rewards(item, money or exp)
globalNumOfRewards: 0

# Runs for x seconds ; 0 to run until winner
duration: 0 

# Remove items gathered from winner?
removeItems: false

# Enable/disable short message mode (does not display items/rewards/riddles globally)
shortMessageMode: false

# Scheduler setting. See config page on dev bukkit. Default runs hourly.
schedule: "0 * * * *"
enableScheduler: true

# Metrics setting. You can opt-out of metrics by setting this to false.
# All collected data is sent anonymously
enableMetrics: true