name: ScavengerHunt
version: 1.7.2-SNAPSHOT
authors: [Fireworks, Zonedabone, Rehv]
softdepend: ['Vault']

main: net.mysticrealms.fireworks.scavengerhunt.ScavengerHunt

commands:
  scavengerstart:
    usage: /<command>
    description: Start scavenger event.
    permission: scavengerhunt.start
  scavengerstop:
    usage: /<command>
    description: Stop scavenger event.
    permission: scavengerhunt.stop
  scavengeritems:
    usage: /<command>
    description: List scavenger items.
    permission: scavengerhunt.items
  scavengerrewards:
    usage: /<command>
    description: List scavenger rewards.
    permission: scavengerhunt.rewards
  scavengerreload:
    usage: /<command>
    description: Reload configuration.
    permission: scavengerhunt.reload
  scavengerjoin:
    usage: /<command>
    description: Join current scavenger event.
    permission: scavengerhunt.participate
  scavengerhelp:
    usage: /<command>
    description: Displays help menu.

permissions:
  scavengerhunt.start:
    default: op
    description: Grants ability to start scavenger event.
  scavengerhunt.participate:
    default: true
    description: Grants ability to participate in scavenger event.
  scavengerhunt.stop:
    default: op
    description: Grants ability to stop scavenger event.
  scavengerhunt.items:
    default: true
    description: Grants ability to list scavenger items.
  scavengerhunt.rewards:
    default: true
    description: Grants ability to list scavenger rewards.
  scavengerhunt.reload:
    default: op
    description: Grants ability to reload config.